### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by goldjee** [ags131/steamMinigameSlaveScript#2]
At start spawns 4 slaves (setting set to 5). No buttons 'Spawn/kill' are shown.

**Comment by ags131** [comment]
Its spawning 5 windows here, and the buttons have been moved down next to the sound toggles. 
You using firefox or chrome?

**Comment by goldjee** [comment]
Latest Chrome

**Comment by ags131** [comment]
I'm closing this as I'm unable to reproduce, you may want to try forcing an update to newest version.
